### ISSUE TITLE
systemd is installed due to live-config dependecies

### ISSUE THREAD

**Issue by vinc3nt** [AvANa-BBS/freepto-lb#142]
systemd is installed with an dist-upgrade on the current stable release:

```
root@freepto:/home/paranoid# aptitude why systemd
i   live-config         Dipende  live-config-sysvinit | live-config-backend
p   live-config-systemd Fornisce live-config-backend                       
p   live-config-systemd Dipende  systemd 
```
we should avoid that this package will be installed on freepto

**Comment by intrigeri** [comment]
Note that merely installing the systemd package doesn't magically make it the init system.

**Comment by boyska** [comment]
On Mon, Jun 22, 2015 at 08:04:37AM -0700, intrigeri wrote:

> Note that merely installing the systemd package doesn't magically make it the init system.

sure, but it is probably unneeded

**Comment by boyska** [comment]
I think that we could close this as a wontfix: it has no consequences, and our efforts should be towards "chips" release, to be based on jessie, so with systemd
